//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.dbo_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_tbl
    {
        public int Emp_Id { get; set; }
        public string Emp_name { get; set; }
        public string Emp_Department { get; set; }
        public Nullable<int> Emp_sal { get; set; }
        public string Emp_mob { get; set; }
        public string Emp_company { get; set; }
    }
}
